import = [
    # Color Schemes
    # "~/.config/alacritty/themes/catppuccin-frappe.toml"
    # "~/.config/alacritty/themes/catppuccin-latte.toml"
    # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    "~/.config/alacritty/themes/catppuccin-mocha.toml",
    # "~/.config/alacritty/themes/rose-pine-dawn.toml"
    # "~/.config/alacritty/themes/rose-pine-moon.toml"
    # "~/.config/alacritty/themes/rose-pine.toml"
    #
    # Platform
    "~/.config/alacritty/platforms/mbp16.toml"
]

[env]
TERM = "xterm-256color"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
option_as_alt = "OnlyLeft"
