import = [
    # Color Schemes
    # "~/.config/alacritty/themes/catppuccin-frappe.toml"
    # "~/.config/alacritty/themes/catppuccin-latte.toml"
    # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
    # "~/.config/alacritty/themes/rose-pine-dawn.toml"
    # "~/.config/alacritty/themes/rose-pine-moon.toml"
    # "~/.config/alacritty/themes/rose-pine.toml"
    #
]

[env]
  TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
option_as_alt = "OnlyLeft"
