#! /bin/sh

# cursor
xsetroot -cursor_name arrow

export GDK_DPI_SCALE=1.5

. /home/midwest/.config/themes/themes.sh
theme_set_bg

# dunst
dunst -config ~/.config/dunst/dunstrc &

# picom
picom --experimental-backends &

# keyboard
. /home/midwest/.config/bspwm/xkbmap

bspc monitor -d DEV WEB MSG ' 4 ' ' 5 ' ' 6 ' ' 7 ' ' 8 ' BG
polybar --config=/home/midwest/.config/polybar/config main &
sxhkd &

# Borders and gaps
bspc config border_width            4
bspc config window_gap              16
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config top_monocle_padding     -5

# Border colors
bspc config normal_border_color     "#524f67"
bspc config focused_border_color    "#eb6f92"
bspc config urgent_border_color     "#B58900"
bspc config presel_border_color     "#26E2FF"
bspc config presel_feedback_color   "#ab87d1"

# Behaviour
bspc config split_ratio             0.5
bspc config auto_alternate          true
bspc config auto_cancel             true
bspc config initial_polarity        first_child

# Rules
bspc rule -a "*:*:Closing Cascadeur" state=floating
